### ISSUE TITLE
full instrumentation or sampling instrumentation?

### ISSUE THREAD

**Issue by wanglu1991** [NVlabs/NVBit#10]
For the mem-trace tool, I found the instrumentation overhead is big for the first execution of one kernel while it is neglectable for other execution. Does it mean that memory tracing is only instrumented once for one kernel? (sampling instrumentation)

**Comment by ovilla** [comment]
The instrumentation is **applied** the first time a kernel (uniquely identified by its name and function pointer) is launched.  That is an added cost.

The instrumentation is **run** by default on every launch, but it can selectively be enabled/disable using the nvbit API. The mem-trace tool runs the instrumentation on every launch.

Please refer to our paper for an explanation of the overheads.

**Comment by wanglu1991** [comment]
Thanks
