### ISSUE TITLE
Texture Memory Reference

### ISSUE THREAD

**Issue by JRPan** [NVlabs/NVBit#105]
Hi, 

I'm trying to dump addresses for load and stores. I can see the memory address correctly printed for all instructions except TEX. For TEX, there is no memory reference. Does TEX require special handling? Or it's not supported? 
I'm using `nvbit_add_call_arg_mref_addr64` to get the memory reference.

Thank you in advance! 
JR

**Comment by ovilla** [comment]
The automatic generation of memory references out of texture instruction operands is not supported in nvbit.
You could still create the memory references manually if you know how texture instruction operands are used to create memory references.
