### ISSUE TITLE
cudaErrorPeerAccessUnsupported Error with NVBit

### ISSUE THREAD

**Issue by Palwisha-18** [NVlabs/NVBit#11]
I am facing issue running applications with NVBit that use cudaDeviceEnablePeerAccess in the program. nvbit tools such as instr_count give cudaErrorPeerAccessUnsupported error. One such example is simpleP2P in cuda samples (cuda/samples/0_Simple/simpleP2P).
<img width="817" alt="uvaproblem" src="https://user-images.githubusercontent.com/29199415/75754915-a113b400-5d3e-11ea-9454-120d2273cb35.PNG">

simpleP2P runs successfully without NVBit.
<img width="656" alt="simpleP2PwithoutNVBit" src="https://user-images.githubusercontent.com/29199415/75754941-af61d000-5d3e-11ea-9410-6322fd196f01.PNG">

I am running nvbit on nvidia DGX-2 with cuda driver version 418.116.00
<img width="600" alt="driver_version" src="https://user-images.githubusercontent.com/29199415/75755096-0667a500-5d3f-11ea-8cd6-662aa441d94c.PNG">

**Comment by ovilla** [comment]
Tried to repro this on latest version of NVBit, but all run as expected on DGX-2. 
Closing for now, please reopen with more info if this issue still exists.
