### ISSUE TITLE
Problem with LDC instruction

### ISSUE THREAD

**Issue by brad-mengchi** [NVlabs/NVBit#12]
Hello,

I cannot get the source register number for constant load instruction: LDC.64 R18, c[0x2][R12];

Below are the info about operand 1:
   op[1].type     = CBANK
   op[1].is_neg/abs  = 0/0
   op[1].value[0] = 2 (2.000000e+00)
   op[1].value[1] = 0 (0.000000e+00)

op[1].value[1] should give me 12 but actually give me 0.

Am I wrong to use the tool or might it be a problem in NVBit?

Thanks!

**Comment by ovilla** [comment]
Yes, it is a bug. Thanks for reporting, we will fix in the next version.

**Comment by x-y-z** [comment]
It should be fixed in NVBit 1.4.
