### ISSUE TITLE
Any update on NVbit?

### ISSUE THREAD

**Issue by mahmoodn** [NVlabs/NVBit#128]
Is there any news about the newer versions of NVbit? The last release was more than 2 years ago and with respect to rapid changes in architectures and applications, NVbit plays a vital rule for researchers. I don't know what is the plan for that? Is it a discontinued product?

**Comment by TylerMG26** [comment]
Waiting to hear about this as well. Looking forward to the next release!

**Comment by rodhuega** [comment]
Me too. It will be nice to have support for the new versions of CUDA and newer architectures such as Ada and Hopper!

**Comment by sun-lingyu** [comment]
Waiting for an update to support Jetson Orin (SM87)...
