### ISSUE TITLE
is there any plan to support NVIDIA xavier? 

### ISSUE THREAD

**Issue by yongchaoding** [NVlabs/NVBit#19]
As above

**Comment by x-y-z** [comment]
We have not tested NVBit on Xavier yet. But if you have JetPack 4.4 on Xavier, feel free to give it a try. NVBit should work. 

Let us know whether it works. Thanks.

**Comment by ovilla** [comment]
Closing this issue, although we don't have tested we believe the code should support it. We will re-open if issue is reported again.
