### ISSUE TITLE
Instrumenting a specific kernel

### ISSUE THREAD

**Issue by trinayan** [NVlabs/NVBit#23]
Thanks for making this really useful tool public. I want to know if it is possible to instrument a specific kernel of interest rather than a whole  application. Or some mechanism in which the metrics can be collected kernel wise when a application has multiple kernels. Thank you.

**Comment by x-y-z** [comment]
You can use the function below to specify which kernel to instrument.

```
/* Run instrumented on original function (and its related functions)
 * based on flag value */
void nvbit_enable_instrumented(CUcontext ctx, CUfunction func, bool flag,
                               bool apply_to_related = true);
```

**Comment by trinayan** [comment]
thanks for the info. Also applications that use internal libraries where the kernel names are mangled in nvprof output, do we have to insert the demangled kernel name in this function?

**Comment by x-y-z** [comment]
No. You only need to keep `apply_to_related = true`, which will enable instrumentation for functions called by this function.

**Comment by trinayan** [comment]
Thanks for the guidance. :)
