### ISSUE TITLE
(Core Dumped) 'std::out_of_range' issue

### ISSUE THREAD

**Issue by cesar-avalos3** [NVlabs/NVBit#32]
Hello,
I'm trying to run the opcode_hist tool using the "hybrid-sort" app from rodinia 3.1, and this error shows up after analyzing a single kernel, 

            terminate called after throwing an instance of 'std::out_of_range'
            what():  _Map_base::at

I'm running a V100, CUDA 11.1, NVBit 1.5.1, cuDNN 8.0.5 (though this program doesn't use any fancy libraries), GCC 7.5.0.
I'm using these arguments:

LD_PRELOAD=../../../../tracer_nvbit/nvbit_release/tools/opcode_hist/opcode_hist.so hybridsort-rodinia-3.1 r 

It finishes fine using instr_count. Several other applications from the Parboil suite show the same issue.

**Comment by x-y-z** [comment]
There is some issue in public NVBit decoding code. We will make a release to fix it. Thanks for filing the issue.

**Comment by x-y-z** [comment]
We just released v1.5.2, which includes the fix to this issue. Let us know if it works for you. Thanks.

**Comment by ovilla** [comment]
This issue should be solved in v1.5.2, closing for now. Please reopen if issue shows up again.
