### ISSUE TITLE
Will SM86 be supported?

### ISSUE THREAD

**Issue by liujian883** [NVlabs/NVBit#33]
Hi
 will sm86 be supported? thanks!

**Comment by x-y-z** [comment]
Yes. The support will be added in the next release.

**Comment by leiwen83** [comment]
sm86 seems has little different with sm80, so would 1.5.2 works if I try to use it for sm86?

**Comment by x-y-z** [comment]
> sm86 seems has little different with sm80, so would 1.5.2 works if I try to use it for sm86?

The NVBit code for SM86 is not in 1.5.2 yet. You will get unsupported arch errors.

**Comment by mahmoodn** [comment]
@x-y-z 
Is there any time table for the next release?

**Comment by ovilla** [comment]
We are currently testing it, so we should be able to release it relatively soon if all goes well

**Comment by ovilla** [comment]
version 1.5.3 released with support for Ampere
