### ISSUE TITLE
Turing SM_75 instrumentation

### ISSUE THREAD

**Issue by mkhairy** [NVlabs/NVBit#4]
Hello, 

Is there any plan to support the Turing architecture with SM_75 capability?
right now, when I try to instrument Turing architecture, it gives me this error:
```NVBit ERROR: SM 7.5 name GeForce RTX 2060 not supported```

Thanks!

**Comment by mkhairy** [comment]
Hello,

This is a kind reminder for my question above. Is there any plan to support the Turing architecture on Nvbit?

Thanks!

**Comment by ovilla** [comment]
It is in our radar but we still have not started the port. 
It is hard to give a timeline at this point but it is something that we really would like to have implemented.

**Comment by mkhairy** [comment]
Hello @ovilla I just want to follow-up with you on this. Are there any plans to support Turing SM_75 soon or it is currently in-progress?

**Comment by ovilla** [comment]
We are making steady progress on it, and at this point we are confident it will be supported in the near future. Still lots of testing and debugging but we will get there. Thanks for inquiring.

**Comment by x-y-z** [comment]
NVBit 1.4 now supports Turing.
