### ISSUE TITLE
Can NVBit work with nvprof ?

### ISSUE THREAD

**Issue by IceCY** [NVlabs/NVBit#45]
Hello,

I am trying to profile the execution time of the instrumented kernel (by NVbit) with `nvprof`. However, it seems NVBit callback is not invoked when using `nvprof`.
Specifically, I use the `instr_count` tool for instrumenting the kernel and `vectoradd` for testing. Then executing the following commands:
```
export LD_PRELOAD=/home/ice/nvbit_release/tools/ice_play/ice_play.so
./vectoradd                 # NVBit callback is invoked 
nvprof ./vectoradd          # NVBit callback is not invoked
```

Yours,
IceCY

**Comment by ovilla** [comment]
Unfortunately this is not supported. 

NVBit uses the same loading "hooks" of nvprof (and other NVIDIA profiling/debug tools) so it is either one or the other, there is no way around this limitation at the moment.

**Comment by IceCY** [comment]
Is there any other performance monitor tool that can work with NVBit ?

**Comment by ovilla** [comment]
No, as far as I know unfortunately.

**Comment by IceCY** [comment]
Got it. Thanks very much for your response.

One last small question. I found that the `cuHook` example in Nvidia code sample can work with `nvprof`. Does it means `NVBit` and `nvprof` hook different APIs from `cuHook` ?
