### ISSUE TITLE
Assertion on instrument_function_if_needed() on 3080

### ISSUE THREAD

**Issue by mahmoodn** [NVlabs/NVBit#49]
Hi,
With nvbit-1.5.3 on 3080 (CUDA-11.2), I get an assertion error with the tracer tool.
```
Writing results to ./traces/kernel-100.trace
python3: tracer_tool.cu:185: void instrument_function_if_needed(CUcontext, CUfunction): Assertion `mem_oper_idx == -1' failed.
Aborted (core dumped)
```
The program uses Python3 and CuDNN. Is there anyway to narrow the problem or report a bug?

**Comment by mahmoodn** [comment]
Sorry this is not related to nvbit.

**Comment by SeriousMan-NJ** [comment]
Thank you for your kind reply. I've found the related issue you mentioned in the AccelSim repo. I'll look into the problem there. Thank you.
