### ISSUE TITLE
Issue with getSize() function member in Instr class

### ISSUE THREAD

**Issue by mkhairy** [NVlabs/NVBit#5]
The member function "getSize()" in the "Instr" class that returns the number of loaded/stored bytes by memory instruction, seems to return incorrect results.
For example, instruction like this:

```
LDG.E.64.STRONG.CTA R12, [R2+0x4000];
```

I expect getSize() = 8 since it is LD of 64 bits (8 bytes), however getSize() = 4?!

**Comment by ovilla** [comment]
It looks like there is bug in the "Lifter". I will look into it. 
Thanks for pointing this out.

**Comment by ovilla** [comment]
this issue should be solved with the release of version 1.3
