### ISSUE TITLE
Decoded instruction for async-copy

### ISSUE THREAD

**Issue by mahmoodn** [NVlabs/NVBit#50]
Hi
With the `printDecoded()` function, I see the following information for an async-copy instruction:

```
Instr 418 @ 0x1a20 (6688) - LDGSTS.E.LTC128B.128.ZFILL [R217], [R22.64], P0 ;
  has_guard_pred = 0
  opcode = LDGSTS.E.LTC128B.128.ZFILL/LDGSTS
  memop = GLOBAL_TO_SHARED
  load/store = 0/0
```
Shouldn't be `load/store = 1/1`? The operation is both load and store.

**Comment by x-y-z** [comment]
Yes, you are right. We will fix it in the next release. Thanks.
