### ISSUE TITLE
README.md says driver version <= 450.36, but nvbit seems to work with newer drivers as well

### ISSUE THREAD

**Issue by sree314** [NVlabs/NVBit#57]
I only tried with `instr_count.so` on the supplied `vectoradd` application, but NVBit seems to work with 470.42.01, contradicting the README.

Please update the README. The READMEs in the GitHub repository and in the release package also contradict each other.

GitHub repository README says 450.36

Release README says 450.00

**Comment by ovilla** [comment]
thanks for reporting this, we will update the README with the correct driver version in the next release
