### ISSUE TITLE
How to use nvbit to instrcutment pytroch applications

### ISSUE THREAD

**Issue by luckyq** [NVlabs/NVBit#72]
Now, I have a deep learning task that used PyTorch. 
The command is as follows:
LD_PRELOAD=mem_trace/mem_trace.so  python examples/mnist/main.py

It will not report an error. But also no traces are generated. 

Does it need some preprocessing for running this?

Thanks in advance.

**Comment by ovilla** [comment]
You could try CUDA_INJECTION64_PATH instead of LD_PRELOAD, sometime machine learning frameworks override LD_PRELOAD before the application is actually launched

**Comment by Diksha-Moolchandani** [comment]
Was this resolved? I am getting the following error with the instruction count tool: Cuda error in function 'cudaDeviceSynchronize()' file 'instr_count.cu' in line 226 : an illegal memory access was encountered. @luckyq @ovilla if it is resolved, please let me know.

**Comment by ovilla** [comment]
As far as we know there is no issue in instrumenting pytorch applications. 
The error on the illegal memory access is very likely something unrelated and worth debugging (after proper repro test case).

**Comment by Diksha-Moolchandani** [comment]
Thanks it is resolved

**Comment by elijahberscheid** [comment]
@Diksha-Moolchandani how did you resolve the issue? I am having the same problem with my pytorch program.
