### ISSUE TITLE
Error with Deepbench and GTX1080TI

### ISSUE THREAD

**Issue by rodhuega** [NVlabs/NVBit#78]
Hi, I'm trying to use the tracing tool from accel-sim (which use NVBit) with Deepbench and a gtx 1080ti. I have run successfully the apps without using the tracer tool, So I suppose that cudnn is installed correctly.  It seems that the error is related with NVBit because it gives errors related with assertions. For example: 

```
rnn_bench: arch/gm10x_hal.cpp:181: void set_imm_relative_control_flow(uint64_t*, int64_t): Assertion `!IS_LARGER_THAN_24BIT(imm)' failed.
run.sh: line 2: 25206 Aborted                 (core dumped) LD_PRELOAD=/media/rodhuega/accel/accelsimV120/util/tracer_nvbit/tracer_tool/tracer_tool.so /media/rodhuega/accel/accelsimV120/gpu-app-collection/src/..//bin/11.0/release/rnn_bench train half 128 64 15 lstm
```

I have tried to use NVBit 1.5, 1.5.3, 1.5.4.

The cuda version that I'm using is 11.0 with cudnn 8.2.1

Here I attach some output files that maybe are useful
[tracerError.txt](https://github.com/NVlabs/NVBit/files/7977177/tracerError.txt)
[tracerOut.txt](https://github.com/NVlabs/NVBit/files/7977178/tracerOut.txt)
[verboseErr.txt](https://github.com/NVlabs/NVBit/files/7977179/verboseErr.txt)
[verboseErrerr.txt](https://github.com/NVlabs/NVBit/files/7977180/verboseErrerr.txt)
.

**Comment by ovilla** [comment]
Hi, we have a potential fix for that and we will be pushing an new version shortly. Thanks for reporting the issue.

**Comment by rodhuega** [comment]
Hi, thanks. I will tell you if it works when the new release will be available.

**Comment by rodhuega** [comment]
Yes, it is working for me. Many thanks for all
