### ISSUE TITLE
Multiple opcodes concatenated by .

### ISSUE THREAD

**Issue by mahmoodn** [NVlabs/NVBit#8]
I would like to know if there is any document about instructions concatenated by `.` in cuda references? I want to know what is the difference between `IMAD` and `IMAD.WIDE`? Specifically for the latter, is that a PTX or SASS instruction? I don't see any instructions named WIDE in the instruction [reference](https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html#volta).

**Comment by ovilla** [comment]
Closing issue, the documentation of SASS instructions is not public.
However, it can be deduced from the documentation of PTX instructions.
