### ISSUE TITLE
Using Nvbit with docker

### ISSUE THREAD

**Issue by mahmoodn** [NVlabs/NVBit#93]
Is it possible to use Nvbit with MLPerf docker image? I tried to run
```
(mlperf) mahmood@mlperf-inference-mnaderan-x86_64:/work$ LD_PRELOAD=/work/nvbit_release/tools/opcode_hist/opcode_hist.so ___RNNT command___ > output.txt
Segmentation fault (core dumped)
```
Has this been tested before?

**Comment by ovilla** [comment]
We use nvbit with docker images regularly. I am not sure what could be the issue.
Can you please try running with VERBOSE=3 in front of LD_PRELOAD?

**Comment by mahmoodn** [comment]
OK. Apparently, when Nvbit is used, more memory is occupied on the device due to the overhead. Therefore, the batch_size of 128 which is fine when running the application alone, is not workable with Nvbit. When I reduced the batch_size, the problem was fixed.
