### ISSUE TITLE
Nvbit with mpirun

### ISSUE THREAD

**Issue by mahmoodn** [NVlabs/NVBit#96]
Does Nvbit work with mpirun command? Apparently, 
```
LD_PRELOAD=~/nvbit-1.5.5/tools/mem_trace/mem_trace.so \
mpirun -np 2 lmp_mpi -sf gpu -in in.test
```
doesn't print the memory addresses, while without `mpirun -np 2` it is fine. Any comment on that?

**Comment by ovilla** [comment]
It should work, we use it all the time, try also `CUDA_INJECTION64_PATH` instead of `LD_PRELOAD`, and try with absolute path starting from "/" instead of "~".
Please report with actual repro instructions if still does not work, we will eventually take a look at it.
Thanks.
